# Generated by Django 6.0.4 on 2026-04-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientocontable',
            name='origen',
            field=models.CharField(choices=[('manual', 'Manual'), ('venta', 'Venta'), ('compra', 'Compra')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='origen_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
