# Generated by Django 6.0.4 on 2026-04-22 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intentos_maximos', models.IntegerField(default=5)),
                ('tiempo_bloqueo_minutos', models.IntegerField(default=30)),
                ('sesion_expira_minutos', models.IntegerField(default=480)),
                ('requiere_2fa', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Configuración de Seguridad',
                'verbose_name_plural': 'Configuración de Seguridad',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=200)),
                ('modulo', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('exitoso', models.BooleanField(default=True)),
                ('detalle', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Acceso',
                'verbose_name_plural': 'Auditoría de Accesos',
                'ordering': ['-fecha'],
            },
        ),
    ]
